contact_links:
  - name: ğŸ’¬ Otaku Social ãŠå•ã„åˆã‚ã›
    url: https://otaku-social.com/contact.php
    about: Otaku Social ãŒé‹å–¶ã™ã‚‹ã‚µãƒ¼ãƒãƒ¼ã«é–¢ã™ã‚‹ãŠå•ã„åˆã‚ã›ã¯ã“ã¡ã‚‰ã€‚ï¼ˆã‚¢ã‚«ã‚¦ãƒ³ãƒˆã‚’ãŠæŒã¡ã®å ´åˆã¯DMã§ã‚‚OKã§ã™ã€‚ï¼‰
  - name: ğŸ’¬ Misskey official Discord
    url: https://discord.gg/Wp8gVStHW3
    about: Chat freely about Misskey
  # ä»®
  - name: ğŸ’¬ Start discussion
    url: https://github.com/misskey-dev/misskey/discussions
    about: The official forum to join conversation and ask question
